[package]
name = "glitchfuck"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
tiny-gradient = "0.1.0"
image = "0.24.4"
unroll = "0.1.5"
egg-mode = "0.16"
crossbeam = "0.8"

[[bin]]
name = "glitchfuck"
path = "src/main.rs"
