TwitterConsumerKey=""
TwitterConsumerSecret=""
TwitterAccessToken=""
TwitterAccessSecret=""
TwitterInterval=""

DiscordAuthToken=""
DiscordID=""

MastodonInstanceURL=""
MastodonInterval=""
MastodonEmail=""
MastodonPassword=""

InProduction=false